name: Continuous Integration
on: [push] 
jobs: 
  eslint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps: #optional
     - name: Checkout code #required
       uses: actions/checkout@v2

     - name: Install packages
       run: npm i
       
     - name: Run ESline
       run: npm run lint